### ISSUE TITLE
Support for JWKS

### ISSUE THREAD

**Issue by JC000** [xmidt-org/bascule#120]
The current Resolver implementation expects endpoints to provide raw public keys.  We would like support for wrapped keys in either JWK or JWK set format by examining the content-type header of the response from the key URI.

**Comment by johnabass** [comment]
I'm assuming they are using the RFC MIME types of `application/jwk+json` for a single key and `application/jwk-set+json` for multiple keys, as defined in https://datatracker.ietf.org/doc/html/rfc7517#section-7.  Even those are to be used for encrypted keys, it seems like the industry is also using them for unencrypted, public keys.

Should we accept `application/json` in order to be permissive?

**Comment by johnabass** [comment]
This is proving to be a much bigger task than I had anticipated.  I've added https://github.com/xmidt-org/bascule/issues/121 to track what I think is the best solution.
